FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

RUN apt-get update && pip install --upgrade pip && pip install pyPEG2
#RUN git clone https://gitea.pep.foundation/fdik/yml2.git && cd yml2 && python3 setup.py install